//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zopa.Estimator.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zopa.Estimator.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The arguments you provided for this command are wrong or missing, please use &apos;help&apos; command to get documentation on how to use the Zyga Estimator
        ///.
        /// </summary>
        public static string ArgumentsErrorMessage {
            get {
                return ResourceManager.GetString("ArgumentsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Unable to find the file &apos;{0}&apos;
        /// .
        /// </summary>
        public static string ErrorFileNotFoundMessage {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan must be between 1000 and 15000 and a multiple of 100.
        /// </summary>
        public static string ErrorLoanNotCorrectMessage {
            get {
                return ResourceManager.GetString("ErrorLoanNotCorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The value &apos;{0}&apos; is not a valid number
        ///.
        /// </summary>
        public static string ErrorLoanNotFloatMessage {
            get {
                return ResourceManager.GetString("ErrorLoanNotFloatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The csv file doesn&apos;t contain correct data.
        /// </summary>
        public static string ErrorWrongData {
            get {
                return ResourceManager.GetString("ErrorWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Zyga Estimator requires 2 arguments to calculate the best rate for your loan
        ///[market file | CSV file] [Loan Amount | floating number]
        ///.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly repayment: £{0}.
        /// </summary>
        public static string MonthlyRepaymentMessage {
            get {
                return ResourceManager.GetString("MonthlyRepaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no offer for the loan asked.
        /// </summary>
        public static string NoOfferMessage {
            get {
                return ResourceManager.GetString("NoOfferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate: {0}%.
        /// </summary>
        public static string RateMessage {
            get {
                return ResourceManager.GetString("RateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount: £{0}.
        /// </summary>
        public static string RequestedAmountMessage {
            get {
                return ResourceManager.GetString("RequestedAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total repayment: £{0}.
        /// </summary>
        public static string TotalRepaymentMessage {
            get {
                return ResourceManager.GetString("TotalRepaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current market data item format for line {0} isn&apos;t respected (Name, Rate | float, Available | int).
        /// </summary>
        public static string WarningMarketDataItemFormat {
            get {
                return ResourceManager.GetString("WarningMarketDataItemFormat", resourceCulture);
            }
        }
    }
}
